/*global chrome*/
import React from 'react';
import ImageAnnotation from '../ImageAnnotation/ImageAnnotation';
import './Report.css'
import it from '../../images/IrishTimes.PNG'
import consent from '../../images/consent.png'
import Tabs from 'react-bootstrap/Tabs'
import Tab from 'react-bootstrap/Tab'

class Report extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            file: null
        };
        this.imgChange = this.imgChange.bind(this)
        this.printState = this.printState.bind(this)
    }

    printState = () => {
        console.log(this.state);
    }

    imgChange = (event) => {
        this.setState({
            file: URL.createObjectURL(event.target.files[0])
        }, this.printState)
    }

    render() {

        var images = [
            {
                "img": it,
                "url": "www.",
                "time": "24/03/2021 18:00 GMT"
            },
            {
                "img": consent,
                "url": "www.",
                "time": "24/03/2021 18:00 GMT"
            }
        ]

        
        return (
            <div className="report">
                <div class="row">
                    <div class="col-12">
                        <div className="imgAnnot">
                            {
                                <Tabs defaultActiveKey="0" className="no-print" id="uncontrolled-tab-example">
                                    {
                                        images != undefined ?
                                            images.map((imageObj, i) => (
                                                <Tab eventKey={i} title={"Screenshot " + (i + 1)} >
                                                    <ImageAnnotation img={imageObj.img} i={i} url={imageObj.url} time={imageObj.time} />
                                                </Tab>
                                            ))
                                            :
                                            null
                                    }
                                </Tabs>
                            }
                            <p className="genMsg">This doc was generated by ___________</p>
                        </div>
                    </div>

                </div>
            </div>
        );
    }
}

export default Report;
