/*global chrome*/
import React from 'react';
import ImageAnnotation from '../Components/ImageAnnotation/ImageAnnotation';
import './Report.css'

import Tabs from 'react-bootstrap/Tabs'
import Tab from 'react-bootstrap/Tab'
import Help from '../Components/Help/Help';
import Facebook1 from '../images/Facebook/Facebook1.PNG'
import Facebook2 from '../images/Facebook/Facebook2.PNG'
import Facebook3 from '../images/Facebook/Facebook3.PNG'
import Facebook4 from '../images/Facebook/Facebook4.PNG'

class Facebook extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            file: null
        };
        this.imgChange = this.imgChange.bind(this)
        this.printState = this.printState.bind(this)
    }

    printState = () => {
        console.log(this.state);
    }

    imgChange = (event) => {
        this.setState({
            file: URL.createObjectURL(event.target.files[0])
        }, this.printState)
    }

    render() {

        var images = [
            {
                "img": Facebook1,
                "url": "www.Facebook.com",
                "time": "Wed, 14 Apr 2021 13:17:30 GMT"
            },
            {
                "img": Facebook2,
                "url": "www.Facebook.com",
                "time": "Wed, 14 Apr 2021 13:17:30 GMT"
            },
            {
                "img": Facebook3,
                "url": "www.Facebook.com",
                "time": "Wed, 14 Apr 2021 13:17:30 GMT"
            },
            {
                "img": Facebook4,
                "url": "www.Facebook.com",
                "time": "Wed, 14 Apr 2021 13:17:30 GMT"
            }
        ]

        
        return (
            <div className="report">
               
                <Help className="no-print"/>

                <div class="row">
                    <div class="col-12">
                        <div className="imgAnnot uploadedImg row">
                            {
                                <Tabs defaultActiveKey="0" className="no-print" id="uncontrolled-tab-example">
                                    {
                                        images != undefined ?
                                            images.map((imageObj, i) => (
                                                <Tab eventKey={i} title={"Screenshot " + (i + 1)} >
                                                    <ImageAnnotation img={imageObj.img} i={i} url={imageObj.url} time={imageObj.time} />
                                                </Tab>
                                            ))
                                            :
                                            null
                                    }
                                </Tabs>
                                

                            }
                            <p className="genMsg">This doc was generated by <a href="https://brianlunch.github.io/ConsentAnnotationToolSite/#/">https://brianlunch.github.io/ConsentAnnotationToolSite/#/</a></p>
                        </div>
                    </div>

                </div>
            </div>
        );
    }
}

export default Facebook;